services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: axum
    container_name: axum
    volumes:
      - .:/app
    ports:
      - 8080:8080
    working_dir: /app
    tty: true
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pgdata:
    driver: local
